# Generated by Django 5.0.6 on 2024-10-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_alter_album_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='Ratings',
            field=models.CharField(choices=[('one', 1), ('two', 2), ('three', 3), ('four', 4), ('five', 5)], default='3', max_length=10),
        ),
    ]
